[package]
name = "rust-nj"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-bindgen = { version = "4.0" }

[build-dependencies]
# NAPI
node-bindgen = { version = "4.0", features = ["build"] }
# C ffi
bindgen = "0.53.1"